include("../MuZero.jl")
using .MuZero

using Logging
using TensorBoardLogger
using Dates: now, format


env = MuZero.TTTexample.env
benchmark = MuZero.TTTexample.benchmark

path = "results/tictactoe/" * format(now(),"yyyy-mm-dd-THHMM") * "/"
tblogger=TBLogger(path, min_level=Logging.Info)
@info "Run `tensorboard --logdir results` to see results in real-time"

# TRAIN
with_logger(tblogger) do
  @info "params" params=env.params
  # @info "alphalike params" αnns.f.net.hyper
  # @timed learning_step!(env)
  @info "network params" MuZero.TTTexample.simμNetworkHP 
  # @info "Memory Analysis" memory_analysis(env.memory)... "generated by MinMax player"
  @info "Benchmark" run_duel(env, benchmark)...
  mutrain!(env, benchmark=benchmark, path=path)
end
